Change header + Add registration form
jakkemomo/meetups-ui pull request #20
Opened 2024-01-27 13:34 UTC by sakalex

2024-01-27 14:10 UTC, jakkemomo commented on src/widgets/header/Header.module.scss
> +
надо бы избавиться от css модулей и чем раньше сделаем, тем лучше)

2024-01-27 14:29 UTC, algoritmi4 commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +          <Link className="text-neutral-500 hover:text-neutral-950 text-lg font-normal" to={"/login"}>Войти</Link>
Внутрь Link стоит поместить button(https://pudie.ru/articles/606979/). Или вместо Link использовать Button.

2024-01-27 14:29 UTC, algoritmi4 commented on src/features/authentication/login/ui/LoginForm.tsx
> +        <Link className="text-neutral-500 hover:text-neutral-950 text-lg font-normal" to="/registration">Зарегистрируйтесь</Link>
Внутрь Link стоит поместить button(https://pudie.ru/articles/606979/). Или вместо Link использовать Button.

2024-01-27 14:29 UTC, algoritmi4 commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +import { Dispatch, ReactElement, SetStateAction, createContext, useCallback, useContext, useRef, useState} from "react"
Компонент стоит разбить по функциям. 200 строк многовато.

2024-01-27 14:29 UTC, algoritmi4 commented on src/app/appRouter.tsx
> +        path: 'registration',
Роут регистрации обычно называется register

2024-01-27 14:29 UTC, algoritmi4 commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +    console.log(data);
console.log не нужен

2024-01-27 14:29 UTC, algoritmi4 commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +    console.log(`Register with ${form.steps.details.value.email} and ${getValues().password}`);
console.log не нужен.

2024-01-27 14:29 UTC, algoritmi4 commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +    console.log(data);
console.log не нужен.

2024-01-27 18:58 UTC, sakalex commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +          <Link className="text-neutral-500 hover:text-neutral-950 text-lg font-normal" to={"/login"}>Войти</Link>
почему?

2024-01-27 19:03 UTC, sakalex commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +import { Dispatch, ReactElement, SetStateAction, createContext, useCallback, useContext, useRef, useState} from "react"
в этом файле 4 функции каждая из которых не более 50 строк, я не очень понимаю о чем идет речь в твоем комментарии

2024-01-28 12:02 UTC, algoritmi4 commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +          <Link className="text-neutral-500 hover:text-neutral-950 text-lg font-normal" to={"/login"}>Войти</Link>
Тупанул. Я подумал это кнопка регистрации, а там реально ссылка. Все правильно сделано. Во втором случае тоже самое

2024-01-28 14:44 UTC, algoritmi4 commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +import { Dispatch, ReactElement, SetStateAction, createContext, useCallback, useContext, useRef, useState} from "react"
Я думаю, что каждую функцию стоит вынести в отдельный файл, тк в конструкции из 4 функций достаточно сложно разобраться. Тем более, что у тебя из RegistrationForm экспортируется RegistrationMultiStepFormContainer

2024-01-29 12:08 UTC, jakkemomo approved these changes

2024-01-30 13:44 UTC, snurnisyan approved these changes

2024-01-30 13:44 UTC, snurnisyan commented on src/features/authentication/registration/model/RegisterFormSchema.ts
> +    .min(2, { message: 'Имя пользователя должно быть не менее 2 символов' }),
Надо будет не забыть расширить валидацию имени пользователя. Договорились, что там могут быть латиница, кириллица и некоторые спец символы

2024-01-30 13:44 UTC, snurnisyan commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +const FormStateContext = createContext({
createContext лучше заменить на Redux (мы его как раз используем), потому что контекст может порождать нежелательные ререндеры и считается неоптимизированным вариантом. Redux под капотом использует контекст, но оптимизирует его.
Либо можно сделать как было в прошлой версии от Гриши через логику step в регистрации (https://github.com/jakkemomo/meetups-ui/tree/developer-old/src/component/Auth/Registration)

2024-01-30 13:44 UTC, snurnisyan commented on src/features/authentication/registration/ui/RegistrationForm.tsx
> +export function RegisterMultiStepFormContainer({setBGCardType}: IRegisterFormProps): ReactElement {
Каждый компонент, который возвращает React элемент (т.е. рендерит UI) лучше вынести в отдельный файл

2024-02-02 19:17 UTC, snurnisyan requested changes

2024-02-02 19:17 UTC, snurnisyan commented on src/features/authentication/registration/ui/DetailForm.tsx
> +        <Button HTMLType='submit' type='primary' extraClass='mt-5' iconType="next">Далее</Button>
The disabled state of the Button is missing. It's important to add disabled styles according to form input  validation.
In my PR I've added disabled styles in this component and propogate 'disabled' props according to form states like this: 

```
<Button
          HTMLType='submit'
          type='primary'
          disabled={!isValid && isSubmitted}
>
....
```

2024-02-09 11:46 UTC, snurnisyan approved these changes

2024-02-09 11:49 UTC, merged