Update register endpoints
jakkemomo/meetups-ui pull request #38
Opened 2024-02-18 02:47 UTC by sakalex

2024-02-18 02:48 UTC, sakalex commented
![Uploading Screenshot 2024-02-18 at 05.48.05.png…]()

2024-02-22 14:34 UTC, algoritmi4 approved these changes

2024-02-23 11:45 UTC, snurnisyan requested changes

2024-02-23 11:45 UTC, snurnisyan commented on src/features/authentication/registration/ui/DetailForm.tsx
> +              setError('email', {message: "This email address is already in use"});
I suggest to write error message in russian because our users are russian speaking.

2024-03-23 16:30 UTC, merged